# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build: 
    docker: 
      - image: cimg/python:3.10

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run: |
          echo "this is the build job"
          pyenv local calclib
          pip install -r requirements.txt
      # Step 3: run linter and tests
      - run: | 
          echo " this is the test job"
          pyenv local calclib
          flake8 --exclude=venv* --statistics
          pytest -v --cov=calculator